<<<<<<< refs/remotes/origin/master
<<<<<<< refs/remotes/origin/master
function Hd = lowpass
%LOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 11-Aug-2020 22:21:29

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 4000;  % Sampling Frequency

N    = 10;       % Order
Fc   = 512;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);
=======
function y = lowpass(x)
%LOWPASS Filters input x and returns output y.
=======
function Hd = lowpass
%LOWPASS Returns a discrete-time filter object.
>>>>>>> Update lowpass

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 11-Aug-2020 22:21:29

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 4000;  % Sampling Frequency

N    = 10;       % Order
Fc   = 512;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

<<<<<<< refs/remotes/origin/master
>>>>>>> FIR Lowpass
=======
% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);
>>>>>>> Update lowpass

% [EOF]
