function y = lowpass(x)
%LOWPASS Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 11-Aug-2020 22:02:19

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % FIR Window Lowpass filter designed using the FIR1 function.
    %
    % % All frequency values are in Hz.
    % Fs = 4000;  % Sampling Frequency
    %
    % N    = 10;       % Order
    % Fc   = 512;      % Cutoff Frequency
    % flag = 'scale';  % Sampling Flag
    %
    % % Create the window vector for the design algorithm.
    % win = hamming(N+1);
    %
    % % Calculate the coefficients using the FIR1 function.
    % b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [-0.00418524240871736 -0.00107309230099734 ...
        0.0299849262735666 0.11570718763956 0.223051221964362 0.273029997664451 ...
        0.223051221964362 0.11570718763956 0.0299849262735666 ...
        -0.00107309230099734 -0.00418524240871736]);
end

y = step(Hd,double(x));


% [EOF]
